name: Book Service CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          export APP_ENVIRONMENT=test
          pytest
      - name: Create Deployment Package
        run: |
          zip -r deployment_package.zip . -x '*.git*' -x '*__pycache__*' -x '*tests*'
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Book-Service-REST-API
          environment_name: Book-Service-REST-API-env
          version_label: ${{ github.run_id }}
          region: us-east-1
          deployment_package: deployment_package.zip
